### ISSUE TITLE
建议整个简单的 web 网页

### ISSUE THREAD

**Issue by yuelwish** [eyjian/sql2struct#2]
建议整个简单的 web 网页
如题所示，弄个web网页， 收藏地址 打开网页 使用上 都比较方便！

**Comment by eyjian** [comment]
> 建议整个简单的 web 网页 如题所示，弄个web网页， 收藏地址 打开网页 使用上 都比较方便！

弄了简单页面，可以看看
[https://hwten.com/](https://hwten.com/)

**Comment by eyjian** [comment]
> > 建议整个简单的 web 网页 如题所示，弄个web网页， 收藏地址 打开网页 使用上 都比较方便！
> 
> 弄了简单页面，可以看看 https://hwten.com/

有 web 页面的挺多的，做成命令行是考虑方便集成，比如 Makefile 中应用等。

**Comment by yuelwish** [comment]
非常感谢！  我收藏这个页面了。 

可能我这种就是做之前所有的还是得要自己过一遍， 如果直接使用命令行，就需要完全的定制化了。 小白就喜欢简单的！
